export const algorithms = [
  {
    id: "aes",
    name: "AES",
    fullName: "Advanced Encryption Standard",
    category: "Chiffrement Symétrique",
    difficulty: "Intermédiaire",
    description: "AES est l'algorithme de chiffrement symétrique le plus utilisé au monde. Il chiffre des blocs de 128 bits avec des clés de 128, 192 ou 256 bits.",
    longDescription: "L'Advanced Encryption Standard (AES) est un algorithme de chiffrement par blocs adopté comme standard par le NIST en 2001. Il remplace le DES devenu obsolète. AES opère sur des blocs de 128 bits et supporte des clés de 128, 192 ou 256 bits. L'algorithme effectue plusieurs tours de substitution, permutation et mélange des données pour assurer la confidentialité.",
    videoUrl: "https://www.youtube.com/embed/O4xNJsjtN6E",
    keyPoints: ["Chiffrement par blocs de 128 bits","Clés de 128, 192 ou 256 bits","10, 12 ou 14 tours selon la taille de la clé","Opérations: SubBytes, ShiftRows, MixColumns, AddRoundKey"],
    useCases: ["HTTPS/TLS","Chiffrement de disques","VPN","Wi-Fi (WPA2)"],
    color: "bg-blue-500"
  },
  {
    id: "des",
    name: "DES",
    fullName: "Data Encryption Standard",
    category: "Chiffrement Symétrique",
    difficulty: "Débutant",
    description: "DES est un ancien standard de chiffrement utilisant des clés de 56 bits. Il est aujourd'hui considéré comme non sécurisé.",
    longDescription: "Le Data Encryption Standard (DES) a été adopté comme standard fédéral américain en 1977. Il utilise une clé de 56 bits pour chiffrer des blocs de 64 bits en 16 tours de Feistel. La taille réduite de sa clé le rend vulnérable aux attaques par force brute. Remplacé par AES en 2001, il reste important pour comprendre les fondements de la cryptographie.",
    videoUrl: "https://www.youtube.com/embed/J12AueUBGIQ",
    keyPoints: ["Clé de 56 bits (considérée faible)","Blocs de 64 bits","16 tours de réseau de Feistel","Remplacé par AES en 2001"],
    useCases: ["Usage historique","Étude académique","Triple DES (3DES)","Systèmes hérités"],
    color: "bg-orange-500"
  },
  {
    id: "3des",
    name: "3DES",
    fullName: "Triple Data Encryption Standard",
    category: "Chiffrement Symétrique",
    difficulty: "Débutant",
    description: "3DES applique DES trois fois consécutivement pour renforcer la sécurité avec des clés de 112 ou 168 bits.",
    longDescription: "Le Triple DES (3DES ou TDEA) est une extension de DES qui applique l'algorithme DES trois fois à chaque bloc de données. Il existe en deux variantes : EDE (Encrypt-Decrypt-Encrypt) avec 2 ou 3 clés distinctes. Bien qu'il améliore significativement la sécurité de DES, 3DES est lent comparé à AES et n'est plus recommandé pour les nouveaux systèmes. Il est progressivement retiré des standards depuis 2017.",
    videoUrl: "https://www.youtube.com/embed/J12AueUBGIQ",
    keyPoints: ["3 applications successives de DES","Clés de 112 ou 168 bits effectifs","Blocs de 64 bits","Déprécié depuis 2017 par le NIST"],
    useCases: ["Systèmes bancaires legacy","Cartes de paiement (EMV)","VPN anciens","Transition DES → AES"],
    color: "bg-amber-600"
  },
  {
    id: "blowfish",
    name: "Blowfish",
    fullName: "Blowfish Block Cipher",
    category: "Chiffrement Symétrique",
    difficulty: "Intermédiaire",
    description: "Blowfish est un chiffrement par blocs rapide et flexible, connu pour sa clé variable de 32 à 448 bits.",
    longDescription: "Blowfish a été conçu par Bruce Schneier en 1993 comme alternative libre et rapide à DES. Il utilise un réseau de Feistel à 16 tours avec une clé de longueur variable (32 à 448 bits) et des blocs de 64 bits. Sa phase d'initialisation (key schedule) est particulièrement coûteuse, ce qui en fait une bonne base pour bcrypt. Blowfish est libre de droits et très répandu dans les logiciels open source.",
    videoUrl: "https://www.youtube.com/embed/gz8AV0bPaOU",
    keyPoints: ["Clé variable de 32 à 448 bits","Blocs de 64 bits","16 tours de Feistel","Key schedule coûteux — base de bcrypt"],
    useCases: ["bcrypt (hachage mots de passe)","SSH (anciens clients)","OpenVPN","7-Zip"],
    color: "bg-cyan-600"
  },
  {
    id: "rc4",
    name: "RC4",
    fullName: "Rivest Cipher 4",
    category: "Chiffrement Symétrique",
    difficulty: "Débutant",
    description: "RC4 est un chiffrement de flux très simple et rapide. Il est aujourd'hui considéré comme cassé et ne doit plus être utilisé.",
    longDescription: "RC4 (Rivest Cipher 4) est un chiffrement de flux conçu par Ron Rivest en 1987. Contrairement aux chiffrements par blocs, RC4 génère un flux de clés pseudo-aléatoire XORé avec le texte clair. Il a été largement utilisé dans WEP (Wi-Fi), SSL et TLS. Plusieurs vulnérabilités graves ont été découvertes, notamment des biais dans les premiers octets générés. RC4 est interdit dans TLS depuis la RFC 7465 (2015).",
    videoUrl: "https://www.youtube.com/embed/eMHpN1JgwWw",
    keyPoints: ["Chiffrement de flux (pas de blocs)","Clé de 40 à 2048 bits","XOR du flux de clés avec le texte","Interdit dans TLS depuis 2015"],
    useCases: ["WEP (obsolète)","SSL/TLS anciens (obsolète)","Étude académique","Protocoles hérités"],
    color: "bg-red-600"
  },
  {
    id: "chacha20",
    name: "ChaCha20",
    fullName: "ChaCha20 Stream Cipher",
    category: "Chiffrement Symétrique",
    difficulty: "Intermédiaire",
    description: "ChaCha20 est un chiffrement de flux moderne, rapide et sécurisé, conçu par Daniel Bernstein. Utilisé dans TLS 1.3 et Android.",
    longDescription: "ChaCha20 est un chiffrement de flux conçu par Daniel J. Bernstein en 2008, basé sur Salsa20. Il utilise une clé de 256 bits, un nonce de 96 bits et un compteur de 32 bits. ChaCha20 est particulièrement performant sur les processeurs sans accélération matérielle AES, ce qui le rend idéal pour les appareils mobiles. Il est utilisé avec le MAC Poly1305 dans la suite ChaCha20-Poly1305, standard dans TLS 1.3.",
    videoUrl: "https://www.youtube.com/embed/UeIpq-C-GSA",
    keyPoints: ["Chiffrement de flux moderne","Clé de 256 bits, nonce 96 bits","Très rapide sans hardware AES","Standard TLS 1.3 avec Poly1305"],
    useCases: ["TLS 1.3","WireGuard VPN","Android (Google)","Signal Protocol"],
    color: "bg-teal-500"
  },
  {
    id: "idea",
    name: "IDEA",
    fullName: "International Data Encryption Algorithm",
    category: "Chiffrement Symétrique",
    difficulty: "Intermédiaire",
    description: "IDEA est un chiffrement par blocs de 64 bits avec une clé de 128 bits, connu pour sa robustesse et son utilisation dans PGP.",
    longDescription: "IDEA (International Data Encryption Algorithm) a été conçu par James Massey et Xuejia Lai en 1991. Il opère sur des blocs de 64 bits avec une clé de 128 bits en 8,5 tours combinant XOR, addition modulo 2¹⁶ et multiplication modulo 2¹⁶+1. IDEA est célèbre pour avoir été utilisé dans PGP (Pretty Good Privacy). Le brevet a expiré en 2012, rendant l'algorithme entièrement libre.",
    videoUrl: "https://www.youtube.com/embed/dCHm0PNIJT4",
    keyPoints: ["Blocs de 64 bits, clé de 128 bits","8,5 tours combinant XOR, addition, multiplication","Utilisé dans PGP","Brevet expiré en 2012"],
    useCases: ["PGP (Pretty Good Privacy)","OpenPGP","Étude académique"],
    color: "bg-emerald-600"
  },
  {
    id: "cesar",
    name: "César",
    fullName: "Chiffre de César",
    category: "Chiffrement Symétrique",
    difficulty: "Débutant",
    description: "Le chiffre de César est le plus ancien chiffrement connu. Il décale chaque lettre d'un alphabet d'un nombre fixe de positions.",
    longDescription: "Le chiffre de César, utilisé par Jules César pour ses communications militaires, est un chiffrement par substitution monoalphabétique. Chaque lettre est remplacée par la lettre située N positions plus loin dans l'alphabet (modulo 26). Bien que trivial à casser aujourd'hui (seulement 25 décalages possibles), il illustre les concepts fondamentaux de la cryptographie symétrique et de la cryptanalyse.",
    videoUrl: "https://www.youtube.com/embed/sMOZf4GN3oc",
    keyPoints: ["Décalage fixe de l'alphabet","Clé = entier de 1 à 25","Seulement 25 clés possibles (force brute triviale)","Base de la cryptographie par substitution"],
    useCases: ["Introduction à la cryptographie","Étude historique","ROT13 (décalage de 13)","Jeux éducatifs"],
    color: "bg-yellow-600"
  },
  {
    id: "rsa",
    name: "RSA",
    fullName: "Rivest-Shamir-Adleman",
    category: "Chiffrement Asymétrique",
    difficulty: "Avancé",
    description: "RSA est un algorithme de chiffrement asymétrique basé sur la difficulté de factoriser de grands nombres premiers.",
    longDescription: "RSA (Rivest-Shamir-Adleman) est l'un des premiers systèmes de cryptographie à clé publique, inventé en 1977. Sa sécurité repose sur la difficulté de factoriser le produit de deux grands nombres premiers. Chaque utilisateur possède une paire de clés : une clé publique pour chiffrer et une clé privée pour déchiffrer. RSA est largement utilisé pour l'échange sécurisé de clés et les signatures numériques.",
    videoUrl: "https://www.youtube.com/embed/wXB-V_Keiu8",
    keyPoints: ["Cryptographie à clé publique","Basé sur la factorisation de grands nombres","Tailles de clé recommandées : 2048+ bits","Utilisé pour le chiffrement et les signatures"],
    useCases: ["Signatures numériques","Échange de clés","Certificats SSL","Email chiffré (PGP)"],
    color: "bg-purple-500"
  },
  {
    id: "ecc",
    name: "ECC",
    fullName: "Elliptic Curve Cryptography",
    category: "Chiffrement Asymétrique",
    difficulty: "Avancé",
    description: "La cryptographie sur courbes elliptiques offre une sécurité équivalente à RSA avec des clés beaucoup plus petites.",
    longDescription: "La cryptographie sur courbes elliptiques (ECC) utilise la structure algébrique des courbes elliptiques sur des corps finis. Une clé ECC de 256 bits offre un niveau de sécurité comparable à une clé RSA de 3072 bits. Cette efficacité la rend idéale pour les appareils mobiles et l'IoT. ECC est utilisée dans ECDSA (signatures), ECDH (échange de clés), et est au cœur de Bitcoin.",
    videoUrl: "https://www.youtube.com/embed/NF1pwjL9-DE",
    keyPoints: ["Clés plus petites que RSA pour sécurité équivalente","Basée sur le problème du logarithme discret elliptique","Idéale pour les appareils à ressources limitées","Utilisée dans Bitcoin (courbe secp256k1)"],
    useCases: ["Bitcoin / Ethereum","TLS moderne","Appareils IoT","Signatures numériques"],
    color: "bg-indigo-500"
  },
  {
    id: "elgamal",
    name: "ElGamal",
    fullName: "Système de chiffrement ElGamal",
    category: "Chiffrement Asymétrique",
    difficulty: "Avancé",
    description: "ElGamal est un système de chiffrement asymétrique basé sur le problème du logarithme discret, fondement de nombreux systèmes modernes.",
    longDescription: "Le système ElGamal, publié par Taher ElGamal en 1985, est un algorithme de chiffrement à clé publique basé sur l'échange Diffie-Hellman. Sa sécurité repose sur la difficulté du problème du logarithme discret. Une propriété intéressante est son caractère probabiliste : le même message chiffré deux fois donnera deux chiffrés différents grâce à un entier aléatoire k. ElGamal est à la base de DSA et d'autres protocoles.",
    videoUrl: "https://www.youtube.com/embed/nLcGAx4bkiU",
    keyPoints: ["Basé sur le logarithme discret","Chiffrement probabiliste","Clé chiffrée deux fois plus longue que le message","Fondement de DSA"],
    useCases: ["GPG (GNU Privacy Guard)","Protocoles de vote électronique","Cryptographie post-quantique","Signatures numériques"],
    color: "bg-violet-600"
  },
  {
    id: "dsa",
    name: "DSA",
    fullName: "Digital Signature Algorithm",
    category: "Chiffrement Asymétrique",
    difficulty: "Avancé",
    description: "DSA est un standard de signature numérique basé sur ElGamal, adopté par le NIST. Il garantit l'authenticité et l'intégrité.",
    longDescription: "Le Digital Signature Algorithm (DSA) a été proposé par le NIST en 1991 et adopté comme standard fédéral (FIPS 186). Basé sur ElGamal, DSA est conçu uniquement pour les signatures, pas pour le chiffrement. Il génère une signature (r, s) à partir d'un message et d'une clé privée. ECDSA (DSA sur courbes elliptiques) est la variante moderne utilisée dans Bitcoin, TLS et les certificats numériques.",
    videoUrl: "https://www.youtube.com/embed/iS1nK4G6EtA",
    keyPoints: ["Uniquement pour les signatures (pas de chiffrement)","Standard NIST (FIPS 186)","Signature = paire (r, s)","ECDSA = variante sur courbes elliptiques"],
    useCases: ["Certificats numériques (X.509)","Bitcoin (ECDSA)","SSH (clés)","Signatures de code logiciel"],
    color: "bg-fuchsia-600"
  },
  {
    id: "diffie-hellman",
    name: "Diffie-Hellman",
    fullName: "Protocole d'échange de clés Diffie-Hellman",
    category: "Échange de Clés",
    difficulty: "Intermédiaire",
    description: "Diffie-Hellman permet à deux parties d'établir un secret partagé sur un canal non sécurisé.",
    longDescription: "Le protocole Diffie-Hellman, publié en 1976, est le premier protocole d'échange de clés publiques. Il permet à deux parties de créer un secret partagé sans jamais le transmettre directement. Sa sécurité repose sur le problème du logarithme discret. Ce protocole est fondamental dans TLS, SSH et de nombreux autres protocoles de communication sécurisée.",
    videoUrl: "https://www.youtube.com/embed/NmM9HA2MQGI",
    keyPoints: ["Échange de clés sans canal sécurisé","Basé sur le logarithme discret","Ne fournit pas d'authentification seul","Base de Perfect Forward Secrecy"],
    useCases: ["TLS/SSL","SSH","VPN (IPsec)","Messagerie chiffrée"],
    color: "bg-teal-500"
  },
  {
    id: "sha1",
    name: "SHA-1",
    fullName: "Secure Hash Algorithm 1",
    category: "Fonction de Hachage",
    difficulty: "Débutant",
    description: "SHA-1 produit un condensé de 160 bits. Il est considéré comme cassé depuis 2017 et ne doit plus être utilisé.",
    longDescription: "SHA-1, conçu par la NSA et publié en 1995, produit un condensé de 160 bits (40 hex). Longtemps standard, il a été compromis en 2017 quand Google a démontré la première collision pratique (SHAttered). SHA-1 est désormais interdit dans les certificats TLS/SSL et les signatures numériques. Les navigateurs modernes rejettent les certificats signés avec SHA-1.",
    videoUrl: "https://www.youtube.com/embed/kmHojGMUn0Q",
    keyPoints: ["Condensé de 160 bits","Collision trouvée en 2017 (SHAttered)","Interdit dans les certificats TLS","Remplacé par SHA-256 ou SHA-3"],
    useCases: ["Git (identifiants de commits)","Vérification legacy","Systèmes anciens","Étude académique"],
    color: "bg-rose-500"
  },
  {
    id: "sha256",
    name: "SHA-256",
    fullName: "Secure Hash Algorithm 256-bit",
    category: "Fonction de Hachage",
    difficulty: "Intermédiaire",
    description: "SHA-256 produit un condensé de 256 bits à partir de données de taille quelconque. C'est une fonction à sens unique.",
    longDescription: "SHA-256 fait partie de la famille SHA-2 conçue par la NSA. Cette fonction de hachage cryptographique prend une entrée de taille arbitraire et produit un condensé fixe de 256 bits. Elle est résistante aux collisions, aux pré-images et aux secondes pré-images. SHA-256 est au cœur de Bitcoin et est utilisé dans de nombreux protocoles de sécurité.",
    videoUrl: "https://www.youtube.com/embed/f9EbD6iY9zI",
    keyPoints: ["Sortie fixe de 256 bits","Fonction à sens unique (irréversible)","Résistante aux collisions","64 tours de compression"],
    useCases: ["Bitcoin / Blockchain","Vérification d'intégrité","Stockage de mots de passe","Certificats numériques"],
    color: "bg-green-500"
  },
  {
    id: "md5",
    name: "MD5",
    fullName: "Message Digest Algorithm 5",
    category: "Fonction de Hachage",
    difficulty: "Débutant",
    description: "MD5 produit un condensé de 128 bits. Il est considéré comme cassé et ne doit plus être utilisé pour la sécurité.",
    longDescription: "MD5, conçu par Ronald Rivest en 1991, est une fonction de hachage produisant un condensé de 128 bits. Des vulnérabilités majeures ont été découvertes : des collisions peuvent être trouvées en quelques secondes. MD5 ne doit plus être utilisé pour des applications de sécurité, mais reste utile pour la vérification d'intégrité non critique.",
    videoUrl: "https://www.youtube.com/embed/53O9J2J5LBs",
    keyPoints: ["Sortie de 128 bits (32 caractères hex)","Vulnérable aux collisions","Ne doit PAS être utilisé pour la sécurité","Encore utilisé pour les checksums"],
    useCases: ["Checksums de fichiers","Usage historique","Comparaison rapide de données"],
    color: "bg-red-500"
  },
  {
    id: "bcrypt",
    name: "bcrypt",
    fullName: "Blowfish-based password hashing",
    category: "Hachage de Mots de Passe",
    difficulty: "Intermédiaire",
    description: "bcrypt est une fonction de hachage adaptative conçue spécifiquement pour le stockage sécurisé des mots de passe.",
    longDescription: "bcrypt, basé sur le chiffrement Blowfish, est conçu pour le hachage de mots de passe. Sa caractéristique principale est le facteur de coût ajustable qui permet d'augmenter le temps de calcul. Il intègre automatiquement un sel aléatoire pour se protéger des attaques par tables arc-en-ciel. bcrypt reste l'un des choix les plus recommandés pour le stockage de mots de passe.",
    videoUrl: "https://www.youtube.com/embed/O6cmuiTBZVs",
    keyPoints: ["Facteur de coût ajustable","Sel intégré automatiquement","Résistant aux attaques par GPU","Sortie de 184 bits"],
    useCases: ["Stockage de mots de passe","Authentification","Applications web"],
    color: "bg-amber-500"
  },
  {
    id: "argon2",
    name: "Argon2",
    fullName: "Argon2 Password Hashing Function",
    category: "Hachage de Mots de Passe",
    difficulty: "Intermédiaire",
    description: "Argon2 est le vainqueur du Password Hashing Competition (2015). Il est résistant aux attaques GPU et ASIC grâce à sa forte utilisation mémoire.",
    longDescription: "Argon2 a remporté le Password Hashing Competition en 2015 et est aujourd'hui la référence pour le hachage de mots de passe. Il existe en trois variantes : Argon2d (résistant GPU), Argon2i (résistant attaques side-channel), Argon2id (recommandé, combinaison des deux). Il est configurable en termes de temps, mémoire et parallélisme, ce qui le rend très flexible.",
    videoUrl: "https://www.youtube.com/embed/7BdAFbHwkwQ",
    keyPoints: ["Vainqueur du Password Hashing Competition 2015","3 variantes : Argon2d, Argon2i, Argon2id","Configurable : temps, mémoire, parallélisme","Résistant GPU et ASIC"],
    useCases: ["Stockage de mots de passe","Dérivation de clés","Frameworks modernes (PHP 8, etc.)","Applications haute sécurité"],
    color: "bg-lime-600"
  },
  {
    id: "pbkdf2",
    name: "PBKDF2",
    fullName: "Password-Based Key Derivation Function 2",
    category: "Hachage de Mots de Passe",
    difficulty: "Intermédiaire",
    description: "PBKDF2 dérive une clé cryptographique à partir d'un mot de passe en appliquant une fonction pseudo-aléatoire des milliers de fois.",
    longDescription: "PBKDF2 (Password-Based Key Derivation Function 2) est défini dans RFC 2898 et PKCS#5. Il applique une fonction pseudo-aléatoire (typiquement HMAC-SHA1 ou HMAC-SHA256) à un mot de passe avec un sel, répétée un grand nombre d'itérations pour ralentir les attaques par force brute. PBKDF2 est standardisé et largement supporté. Il est moins résistant aux GPUs que bcrypt ou Argon2 car il est peu gourmand en mémoire.",
    videoUrl: "https://www.youtube.com/embed/bGd_BFu4zr8",
    keyPoints: ["Itérations configurables (100K+ recommandé)","Sel obligatoire","Standardisé RFC 2898 / PKCS#5","Moins résistant GPU que bcrypt/Argon2"],
    useCases: ["iOS / macOS (Keychain)","WPA2 (Wi-Fi)","Django (Python)","Dérivation de clés TLS"],
    color: "bg-sky-600"
  }
];

export const categories = [
  { name: "Tous", count: algorithms.length },
  { name: "Chiffrement Symétrique", count: algorithms.filter(a => a.category === "Chiffrement Symétrique").length },
  { name: "Chiffrement Asymétrique", count: algorithms.filter(a => a.category === "Chiffrement Asymétrique").length },
  { name: "Fonction de Hachage", count: algorithms.filter(a => a.category === "Fonction de Hachage").length },
  { name: "Échange de Clés", count: algorithms.filter(a => a.category === "Échange de Clés").length },
  { name: "Hachage de Mots de Passe", count: algorithms.filter(a => a.category === "Hachage de Mots de Passe").length },
];

export const resources = [
  {
    id: 1,
    title: "Introduction à la Cryptographie",
    type: "Article",
    description: "Les bases de la cryptographie expliquées simplement pour les débutants.",
    url: "https://fr.wikipedia.org/wiki/Cryptographie",
    difficulty: "Débutant",
    icon: "BookOpen"
  },
  {
    id: 2,
    title: "Cours Cryptographie - Christof Paar",
    type: "Vidéo",
    description: "Série complète de cours universitaires sur la cryptographie appliquée.",
    url: "https://www.youtube.com/playlist?list=PL6N5qY2nvvJE8X75VkXglSFdLDNSjRuq",
    difficulty: "Intermédiaire",
    icon: "Play"
  },
  {
    id: 3,
    title: "CryptoHack - Challenges",
    type: "Pratique",
    description: "Plateforme interactive pour apprendre la cryptographie par la pratique.",
    url: "https://cryptohack.org/",
    difficulty: "Intermédiaire",
    icon: "Code"
  },
  {
    id: 4,
    title: "The Code Book - Simon Singh",
    type: "Livre",
    description: "L'histoire de la cryptographie, des hiéroglyphes à l'informatique quantique.",
    url: "https://simonsingh.net/books/the-code-book/",
    difficulty: "Débutant",
    icon: "Book"
  },
  {
    id: 5,
    title: "Serious Cryptography - Jean-Philippe Aumasson",
    type: "Livre",
    description: "Guide pratique de la cryptographie moderne pour développeurs.",
    url: "https://nostarch.com/seriouscrypto",
    difficulty: "Avancé",
    icon: "Book"
  },
  {
    id: 6,
    title: "Computerphile - Cryptography Playlist",
    type: "Vidéo",
    description: "Vidéos éducatives sur divers aspects de la cryptographie et la sécurité.",
    url: "https://www.youtube.com/user/Computerphile",
    difficulty: "Intermédiaire",
    icon: "Play"
  },
  {
    id: 7,
    title: "OWASP - Sécurité Web",
    type: "Article",
    description: "Guide de référence pour la sécurité des applications web.",
    url: "https://owasp.org/",
    difficulty: "Intermédiaire",
    icon: "Shield"
  },
  {
    id: 8,
    title: "PicoCTF - CTF pour débutants",
    type: "Pratique",
    description: "Compétition de cybersécurité conçue pour les étudiants.",
    url: "https://picoctf.org/",
    difficulty: "Débutant",
    icon: "Trophy"
  }
];